[package]
name = "inbox"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
rocket = { version = "0.5.1", features = ["secrets"] }
rusqlite = "0.34.0"
lib = { path = "../lib" }
rocket_dyn_templates = { version = "0.2.0", features = ["minijinja"] }
