[package]
name = "scratchpad"
version = "0.1.0"
edition = "2021"

[dependencies]
lib = { path = "../lib" }
reqwest = { version = "0.12.15", features = [ "blocking" ] }
sdl2 = { version = "0.37.0", features = [ "ttf", "image" ] }
